Filter out synthetic predictions from bias/fairness metrics calculation
trustyai-python/trustyai-explainability pull request #225
Opened 2023-06-19 09:57 UTC by tteofili

See #224 

Many thanks for submitting your Pull Request :heart:!

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](https://github.com/trustyai-explainability/trustyai-explainability/blob/main/CONTRIBUTING.md)
- [x] Pull Request title is properly formatted: `FAI-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting main: `[0.3.x] FAI-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

2023-06-19 10:02 UTC, danielezonca reviewed
Can you add a test?

2023-06-28 09:02 UTC, ruivieira requested changes
@tteofili letft a couple of comments

2023-06-28 09:02 UTC, ruivieira commented on explainability-core/src/test/java/org/kie/trustyai/explainability/model/DataframeTest.java
> +        assertThat(df.filterRowsBySynthetic(true).getRowDimension()).isEqualTo(10);
Nitpick: could you add an odd number of predictions so that the number of synthetic and non-synthetic is different or check the actual ids?

2023-06-28 09:02 UTC, ruivieira commented on explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/DisparateImpactRatioEndpointTest.java
> +        assertFalse(Double.isNaN(response.getValue()));
@tteofili I don't fully understand the testing for a NaN in DIR (same for the SPD) in this test.
IMO, should the test perhaps be:
- Add valid data
- Calculate DIR
- Add synthetic data
- DIR should be the same?

2023-07-07 09:23 UTC, danielezonca approved these changes

2023-07-12 10:57 UTC, tteofili commented
/retest

2023-07-12 13:43 UTC, RobGeada commented
/test trustyai-explainability-e2e

2023-07-12 13:56 UTC, ruivieira requested changes
@tteofili, LGTM, thanks.
Is it possible to just remove the generated gRPC client files?

2023-07-12 14:12 UTC, tteofili commented
> Is it possible to just remove the generated gRPC client files?

oh no, that again!
sure, I'll move them out

2023-07-13 15:22 UTC, tteofili commented
/retest

2023-07-13 22:46 UTC, ruivieira commented
/retest

2023-07-17 09:12 UTC, tteofili commented
/retest

2023-07-17 14:39 UTC, tteofili commented
/retest

2023-07-18 09:23 UTC, tteofili commented
/retest

2023-07-18 12:26 UTC, ruivieira approved these changes

2023-07-19 07:30 UTC, RobGeada commented
/test trustyai-explainability-e2e

2023-07-19 09:15 UTC, tteofili commented
/retest

2023-07-19 13:49 UTC, tteofili commented
/retest

2023-07-21 08:36 UTC, merged