Remove usage of kogito-app-build-parent + POM cleanup + .gitignore improvement
trustyai-python/trustyai-explainability pull request #32
Opened 2022-10-27 16:40 UTC by danielezonca

- Removed `kogito-app-build-parent`, now the repo is self contained
- Cleanup POM (removed `quarkus-junit` dependency and moved to `optaplanner-core` dependency)
- Minor `.gitignore` improvements

2022-10-27 21:45 UTC, ruivieira approved these changes
LGTM, thanks @danielezonca

IIUC we will also need to change the pipeline in the Python bindings from `mvn ... -f trustyai-explainability/explainability-core/pom.xml -Pshaded` to `mvn ... -f trustyai-explainability/pom.xml -Pshaded`?

2022-10-28 10:52 UTC, ruivieira requested changes
@danielezonca is it possible to change in https://github.com/trustyai-explainability/trustyai-explainability/blob/d7ae388b0be85974b854bb3ac764a67eb9aa6603/explainability-core/src/test/java/org/kie/trustyai/explainability/local/counterfactual/CounterfactualExplainerTest.java#L99 the access modifier to not be `private`? I think this is failing with the new JUnit dependency:

```
org.junit.platform.commons.JUnitException: @BeforeEach method 'private void org.kie.trustyai.explainability.local.counterfactual.CounterfactualExplainerTest.setup()' must not be private.
```

2022-10-31 15:35 UTC, tteofili approved these changes

2022-10-31 16:41 UTC, ruivieira approved these changes

2022-10-31 16:52 UTC, merged