Ground Truth Uploading
trustyai-python/trustyai-explainability pull request #365
Opened 2023-09-21 13:00 UTC by RobGeada

Added flag to enable data/upload endpoint to receive ground truth data. This will create/access a ground truth dataframe. Datapoint ids will mandatorily correlate across the recorded data and ground truth dataframes, allowing for the retrieval of correlated ground truths. 

NEEDS REBASE

Many thanks for submitting your Pull Request :heart:!

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/trustyai-explainability/trustyai-explainability/blob/main/CONTRIBUTING.md)
- [ ] Pull Request title is properly formatted: `FAI-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.3.x] FAI-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

2023-10-05 15:10 UTC, RobGeada commented
/test trustyai-explainability

2023-10-05 15:10 UTC, RobGeada commented
/test trustyai-explainability-e2e

2023-10-11 08:39 UTC, ruivieira requested changes

2023-10-11 08:39 UTC, ruivieira commented on explainability-service/src/test/java/org/kie/trustyai/service/endpoints/data/DataEndpointTest.java
> +        // sorry for the quad loop
@RobGeada could you create a ticket to optimise this, and replace the comment with the issue link? Thanks.

2023-10-11 08:47 UTC, danielezonca approved these changes

2023-10-11 08:47 UTC, danielezonca commented on explainability-core/src/main/java/org/kie/trustyai/explainability/model/Dataframe.java
> +        calculateIndexHashes();
Minor comment (this is going to always trigger the `calculateIndexHashes()` method but it is going to be a no-op when `internalData` is empty)
```suggestion
    public Dataframe() {
        this(new ArrayList<>(new ArrayList<>()), new Metadata(), new InternalData());
    }

    Dataframe(List<List<Value>> data, Metadata metadata) {
        this(new ArrayList<>(data), metadata, new InternalData());
    }

    Dataframe(List<List<Value>> data, Metadata metadata, InternalData internalData) {
        this.data = new ArrayList<>(data);
        this.metadata = metadata;
        this.internalData = internalData;
        this.idToIDX = new HashMap<>();
        calculateIndexHashes();
```

2023-10-11 12:48 UTC, ruivieira approved these changes

2023-10-11 13:40 UTC, merged