RHOAIENG-8631: Add image data drift
trustyai-python/trustyai-explainability pull request #577
Opened 2024-06-17 20:12 UTC by christinaexyou

Addresses https://issues.redhat.com/browse/RHOAIENG-8631 --> Add image data drift by making the following changes:
- Detects data drift according to divergences in RGB pixel values

2024-06-17 20:13 UTC, christinaexyou commented
/ok-to-test

2024-06-19 08:43 UTC, ruivieira requested changes

2024-06-19 08:43 UTC, ruivieira commented on explainability-core/src/main/java/org/kie/trustyai/metrics/drift/image/ImageDrift.java
> +     * Converts an image to Dataframe whose columns are "Red", "Green", "Blue" by extracting the associated RGB values.
Perhaps we should make a note that alpha channels are ignored?

2024-06-19 08:43 UTC, ruivieira commented on explainability-core/src/main/java/org/kie/trustyai/metrics/drift/image/ImageDrift.java
> +                divergence += p1[i] * Math.log(p1[i] / p2[i]);
What happens when an element of p2 is `0`?
Perhaps catching that case.

2024-06-19 08:43 UTC, ruivieira commented on explainability-core/src/main/java/org/kie/trustyai/metrics/drift/image/ImageDrift.java
> +    public static double KLDivergence(double[] p1, double[] p2){
KLDivergence between two arrays might be useful on its own.
I would move this to a more general utility class for re-use and call that class here.

2024-06-24 15:24 UTC, christinaexyou commented
Changes made:
`main/.../metrics/drift/image/ImageDrift.java`
- adds support for images of data type `double[][][]`
- converts images of dtype `BufferedImage` to `double[][][]`
- takes as inputs a list of a single image or a multiple images, extending to the data drift and anomaly use cases

`main/.../metrics/drift/utils/KLDivergence.java`
- moved KL Divergence to utils folder

`.tests/.../metrics/drift/utils/KLDivergence.java`
- adds tests for inputs of data type `double[][][]`
- adds a test for mixed input types

2024-06-25 08:03 UTC, ruivieira approved these changes

2024-06-25 13:26 UTC, merged